### ISSUE TITLE
Ndev different in Pharmacokinetics and PharmacokineticsPoly?

### ISSUE THREAD

**Issue by JanHasenauer** [genssi-developer/GenSSI#10]
It appears that the orders are different. Is this intentional?

**Comment by genssi-developer** [comment]
In the footnote of Table S4 and S5 of the Supplementary Information document, you will see that Pharmacokinetics was run with two different values Nder. The smaller value, 2, is needed for Table S4, which compares the runtime of the older and newer version. The larger value, 7, is needed for Table S5, where Pharmacokinetics achieves a full rank Jacobian. This is also visible in the saved results files. In other words, in the old version (on R2008), Pharmacokinetics does not succeed, but, in the new version (on R2017a), it succeeds, but requires 7 derivatives and 570 seconds. In contrast, PharmacokineticsPoly requires only 3 derivatives to achieve full rank, and runs in 3.4 seconds.

**Comment by genssi-developer** [comment]
Closed unintentionally.

**Comment by JanHasenauer** [comment]
As PharmacokineticsPoly was previously incorrect (as the wrong outputs were used), I guess that the difference between PharmacokineticsPoly and Pharmacokinetics regarding identifiability should be gone. In this case, I  would use the same number of derivatives for both versions.

Could you please check what you get with the revised version of the conversion to polynomial form?

**Comment by genssi-developer** [comment]
Running Pharmacokinetics with 3 derivatives now achieves full rank and reports global identifiability of all parameters in 11.5 seconds. PharmacokineticsPoly achieves full rank with 3 derivatives and runs in 12.8 seconds and reports the same results. In order to compare the runtime with the old version on R2008, we would need to run Pharmacokinetics with 2 derivatives, which does not achieve full rank, but completes in 7.3 seconds. I'm not sure if we still need this comparison and the footnote in the supplementary information document.

**Comment by JanHasenauer** [comment]
> Running Pharmacokinetics with 3 derivatives now achieves full rank and reports global identifiability of all parameters in 11.5 seconds.

So something changes? The changes I implemented should have left everything the same. Do you have a way to see what has changed?

**Comment by genssi-developer** [comment]
Here is what I can see up to now. The differences are visible by comparing model_information.txt in V2-0-R2017 (the old version) and V2-R2017 (the new version). In both cases, the rank of the Jacobian matrix is full after 3 derivatives. Then, in genssiOrderTableaux, there is an fprint statement for "Symbolic solution(s) of the remaining parameters" (new version). After this, presumably in a "solve" statement (my debugging seems to identify the "solve" statement 10 lines after the fprint), there is a warning, one which always existed in the model, even in the R2008 version. The warning in the old version is
[Warning: Solutions might be lost.] 
The warning in the new version is
[Warning: Cannot solve symbolically. Returning a numeric approximation instead.] 
Question: Is there a known reason why the new version should allow a numeric solution to "solve", where the old version doesn't? I.e., have any options been changed? I don't see any options in the style of fmincon. Maybe there is a difference in the input, allowing a numerical interpretation of the symbolic parameters in the new version.

**Comment by JanHasenauer** [comment]
I'm not aware of such a change.
Could you please check the input statements  to the corresponding "solve" command?

**Comment by JanHasenauer** [comment]
the topic was discussed via email and the results are consistent and correct. differences between the number of derivatives could not be reproduced.
