### ISSUE TITLE
Shorter than expected runtime for some examples

### ISSUE THREAD

**Issue by FFroehlich** [genssi-developer/GenSSI#15]
runExample('BIOMD0000000003'); claims to run for 8000s but finishes in <10s
runExample('BIOMD0000000010'); claims to run for 600s but also finishes in <10s

Is this expected or are the arguments to call GenSSI incomplete/wrong?

**Comment by genssi-developer** [comment]
Yes, this makes sense. The claim you mention is the number coded in the genssiAskForConfirmation call. That number was taken from the Supplementary Information document, which includes the runtimes for all 26 models in GenSSI, and most of them in COMBOS, DAISY, and EAR. In the case of BIOMD0000000003, those numbers were based on analyzing 11 parameters. In the meantime, that model was changed to analyze only 4 parameters (of a total of 13), but without changing the documentation. That's where the difference comes from.

**Comment by JanHasenauer** [comment]
I think it would be good to have this consistent. For the purpose of showing that the SBML models work, I would suggest to use the smaller number of parameters.

**Comment by genssi-developer** [comment]
Here is my suggestion: We keep the smaller number of parameters (4) in the run script, and just change the expected runtime. At the same time, we keep the documentation of the larger number of parameters (11) in the SI document, where the full number of parameters (14) is also documented. This way, the reviewer has a fast-running script, but we also document a version that provides useful information.

**Comment by JanHasenauer** [comment]
would work for me.
