### ISSUE TITLE
bug in code?

### ISSUE THREAD

**Issue by juavid** [genssi-developer/GenSSI#16]
I have noticed that in the function genssiComputeLieDerivatives (line 62) where all combinations of vF and Vg of oder>1 are calculated there might be an error.

(line 72)         Jac  = [Jac;JacF;JacG];

I think that this matrix should be outside the for loop for the number of controls, if not it is used again to calculate the Jacobian at JacTemp for the next input and the same order. This error will not show up for single input systems. I have checked for one example in the toolbox you have for multiple inputs and even though it doesn't seem to affect the final result it adds redundant calculations.

**Comment by JanHasenauer** [comment]
Dear juavid, thanks a lot for posting this issue. The implementation was indeed incorrect (or at least inefficient). I modified the code to address this issue. Please have a look and let us know I you find something else.
Note: For the results provided in the toolbox, the results remains the same.
