### ISSUE TITLE
Error on a toy gene expression model

### ISSUE THREAD

**Issue by dlekshmi** [genssi-developer/GenSSI#17]
Hi, 

I ran into a 'minor' error in GenSSI and would like to report it. 
While trying to do the analysis in GenSSi on the attached model, I run into the following error: 
```
Error using mat2cell (line 89)
Input arguments, D1 through D2, must sum to each dimension of the input matrix size, [0  0].

Error in genssiOrderTableau>solveRemPar (line 659)
        equation_relations=mat2cell(ECC,ones(1,length(ECC)),1);

Error in genssiOrderTableau>displayRemainingParameters (line 636)
            solveRemPar(ECC_remaining,Param_remaining,Param_local,global_ident_par);

Error in genssiOrderTableau (line 212)
                        displayRemainingParameters...

Error in genssiMain (line 137)
    [options,results] = genssiOrderTableau(model,results,RJacParam01,ECC,rParam,options);
```

I attach the execution details along with the model/ script. 

[Issue_DL.zip](https://github.com/genssi-developer/GenSSI/files/1946423/Issue_DL.zip)

[GenSSI_toymodel_DL.pdf](https://github.com/genssi-developer/GenSSI/files/1946413/GenSSI_toymodel_DL.pdf)

This seems to happen because, ``Paramy==ECCx==0`` and ``ECC=[]``.  If this is something that was to be expected due to an oversight on my part do let me know.

**Comment by thomassligon** [comment]
Dear Lekshmi,

thanks for pointing out the issue. I am travelling this week, but I plan to look at this soon.

Tom
(Dr. Thomas S. Ligon)
Tom@thomassligon.info<mailto:Tom@thomassligon.info>
Frohnloher Str. 6a
81475 Muenchen
Germany
Tel. +49(89)74575075

**Comment by thomassligon** [comment]
I added a few lines to avoid empty ECC.
