### ISSUE TITLE
Thyroid1 and Thyroid2 identical

### ISSUE THREAD

**Issue by JanHasenauer** [genssi-developer/GenSSI#6]
I did not find a difference between Thyroid1 and Thyroid2. What is the difference?

**Comment by thomassligon** [comment]
These are COMBOS models, and the difference in the COMBOS versions of Thyroid1 and Thyroid2 is the initial conditions. This difference has somehow been lost in the GenSSI version. I will correct that.

Tom
(Dr. Thomas S. Ligon)
Tom@thomassligon.info<mailto:Tom@thomassligon.info>
Frohnloher Str. 6a
81475 Muenchen
Germany
Tel. +49(89)74575075

**Comment by genssi-developer** [comment]
In COMBOS, Thyroid1 has no initial conditions, and Thyroid2 has all zeros. In GenSSI we have model.sym.x0=[0 0 0] for both models.
Question: Is it possible to define empty initial conditions in AMICI/GenSSI? I tried setting model.sym.x0=[] and the result is not good, i.e. no Lie derivatives, no tableaus. Should we add a check in genssiCheckModel?

**Comment by JanHasenauer** [comment]
I think that GenSSI needs conceptually initial conditions. We should however get the same results if we set the initial conditions in GenSSI to unknown parameters and perform the structural identifiability analysis only with respect to the kinetic parameters.

**Comment by genssi-developer** [comment]
I see that Thyroid1 now has three new parameters, x10, x20, and x30, but they are not used, and x0 is still all zeros.

**Comment by genssi-developer** [comment]
Closed unintentionally.

**Comment by JanHasenauer** [comment]
ah, good point. i included them in x0. now it should be fine.
