### ISSUE TITLE
illustration of genssiTransformation

### ISSUE THREAD

**Issue by JanHasenauer** [genssi-developer/GenSSI#7]
Is the application of genssiTransformation illustrated in one of the examples?

I had a look but did not find it. One possibility would be Transfection2. This could be constructed from Transfection1 using genssiTransformation.

**Comment by JanHasenauer** [comment]
An other example would be NGF_ERK.

**Comment by thomassligon** [comment]
Yes, it is in M2_2 (and in the refman). I will consider renaming and merging this with the Transfectionx examples.

Tom
(Dr. Thomas S. Ligon)
Tom@thomassligon.info<mailto:Tom@thomassligon.info>
Frohnloher Str. 6a
81475 Muenchen
Germany
Tel. +49(89)74575075

**Comment by thomassligon** [comment]
I don’t understand. Example of what?

Tom
(Dr. Thomas S. Ligon)
Tom@thomassligon.info<mailto:Tom@thomassligon.info>
Frohnloher Str. 6a
81475 Muenchen
Germany
Tel. +49(89)74575075

**Comment by JanHasenauer** [comment]
ah, I missed that it is used in these examples.
