### ISSUE TITLE
remove results ./runXXX from github?

### ISSUE THREAD

**Issue by JanHasenauer** [genssi-developer/GenSSI#8]
I think it would be good to remove the results of the runs from the repository. Currently, most of the files are actually results files. 
I would suggest to include a respective command in .gitignore.

(If have to admit that I tried this already but did not succeed.)

**Comment by JanHasenauer** [comment]
Same actually for the BIOMD03.m and BIOMD10.m as they are only generated by the execution of runBIOMD03.m and runBIOMD10.m , respectively.

**Comment by thomassligon** [comment]
I don’t agree. The results are an important part of the documentation.

Tom
(Dr. Thomas S. Ligon)
Tom@thomassligon.info<mailto:Tom@thomassligon.info>
Frohnloher Str. 6a
81475 Muenchen
Germany
Tel. +49(89)74575075

**Comment by thomassligon** [comment]
Same answer: We need the results in order to document what works.

Tom
(Dr. Thomas S. Ligon)
Tom@thomassligon.info<mailto:Tom@thomassligon.info>
Frohnloher Str. 6a
81475 Muenchen
Germany
Tel. +49(89)74575075

**Comment by JanHasenauer** [comment]
Dear Tom,

I think we should distinguish between the documentation and the tool itself. For the documentation, one could argue that the results are useful. However, what use do they have for a user of the tool? Do we expect them to look at the examples? (I wouldn't.)

Complementarily, if we do not include the file run files in the .gitignore, everybody how wants to develop and use the tools has to do it themselves. If a run an example, a new ./runXX file is generate and I have to explicitly exclude it in the commit to github. This is in my opinion not ideal.

Greetings, Jan

**Comment by thomassligon** [comment]
Hello Jan,

well, I don’t explicitly exclude run1, run2, etc., but just delete them. If we don’t replicate the older results to GitHub, they will just be archived on my PC, where no one has access, which is very much against the idea of GitHub.

Tom
(Dr. Thomas S. Ligon)
Tom@thomassligon.info<mailto:Tom@thomassligon.info>
Frohnloher Str. 6a
81475 Muenchen
Germany
Tel. +49(89)74575075

**Comment by JanHasenauer** [comment]
Dear Tom,

what do you think about generating a release after finishing all the revisions which includes the results of the runs. That way the results are public and documented. After the release is generated, we could remove the results.
This way:
1) we would not always have to regenerate the results after changing something in GenSSI, and
2) the toolbox would not fill up with stuff not used by the users.

-- Jan

**Comment by thomassligon** [comment]
Hello Jan,

that sounds like a very good idea. It would archive the old results in GitHub, but we wouldn’t need to replicate (or manually delete) newer results. (I might need some help in how to create a release in GitHub.)

Tom
(Dr. Thomas S. Ligon)
Tom@thomassligon.info<mailto:Tom@thomassligon.info>
Frohnloher Str. 6a
81475 Muenchen
Germany
Tel. +49(89)74575075

**Comment by JanHasenauer** [comment]
Great. Then let's do this.
