### ISSUE TITLE
Message: "Test warning: Does this ever happen?"

### ISSUE THREAD

**Issue by JanHasenauer** [genssi-developer/GenSSI#9]
For the current implementation of BIOMD0000000003, I receive somewhere in the middle the message: "Test warning: Does this ever happen?"
It is not clear why this is useful and it should probably be removed.

**Comment by thomassligon** [comment]
This is line 319 of genssiOrderTableau

it could be
1) removed
2) changed to “unexpected error” or “errare humanum est”
In any case, it is something that I never understood (and probably never will).

Tom
(Dr. Thomas S. Ligon)
Tom@thomassligon.info<mailto:Tom@thomassligon.info>
Frohnloher Str. 6a
81475 Muenchen
Germany
Tel. +49(89)74575075

**Comment by JanHasenauer** [comment]
Okay, I checked the code. In my understanding, this simply means that after reduction ECC is 0 which is equivalent to it being empty. I simply removed the text.
